### ISSUE TITLE
modeler lost parameters

### ISSUE THREAD

**Issue by ouyangshixiong** [Activiti/activiti-modeling-app#112]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
process variable added in the modeler tool, didn't saved into diagram xml file.

**Expected behavior:**
process variables should saved in diagram xml file

**Steps to reproduce the issue:**
1. setup k8s cluster
2. install Activiti Cloud
3. login into modeler application, create project, create process diagram.
4. edit process variables, add a var named my_variable.
5. save the diagram, download it 
6. open Sublime text, find character "my_variable", not found

**Component name and version:** 
7.0.0.SR1

**Browser and version:** 
Chrome

**Comment by ouyangshixiong** [comment]
![](https://files.gitter.im/Activiti/Activiti7/yo1H/image.png)

**Comment by rdiacenco** [comment]
This is not an issue. 
The steps describe the expected behavior. 
Process variables and mappings **are not saved in the XML** file.
This information is available in the **process-extensions.json** file, that can be seen in the **project.zip** exported archive.

**Comment by ouyangshixiong** [comment]
@rdiacenco I found that file now, Thank you for your help.
