### ISSUE TITLE
[Question] Is there any way to use different access management system then keycloack?

### ISSUE THREAD

**Issue by mkawczynski07** [Activiti/activiti-modeling-app#23]
In our project, we use activiti core version and we would like to have modeler on board. We are using jHipster UAA microservice as the access management system. In case of that, I changed app.config.json. But unfortunately, a modeler in the development mode still try to use keycloack from **activiti-keycloak.35.204.66.71.nip.io.**   So the question is could we use different oAuth2 config?

**Comment by fcorti** [comment]
Hi @mkawczynski07 ,

Sorry for the late reply.

This is more a question for Activiti, than the Modeler app.
I'm afraid the answer won't be positive, but I suggest you to try to raise the question in https://gitter.im/Activiti/Activiti7 

I hope this will help you.

Cheers.

**Comment by mkawczynski07** [comment]
@fcorti using @daisuke-yoshimoto integration example We were able to integrate modeler with jhipster uaa by forwarding auth request to uaa.

**Comment by fcorti** [comment]
Oh.. great... thank you for the heads up.
