### ISSUE TITLE
activiti show blank page after npm start and errors in console log

### ISSUE THREAD

**Issue by bikabdel** [Activiti/activiti-modeling-app#252]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

Activiti isn't lunching on browser showing blank page
**Expected behavior:**

activiti show the authentification interface 
**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 chrome
**Node version (for build issues):**  

**New feature request:**

![Capture d’écran de 2019-10-18 16-17-15](https://user-images.githubusercontent.com/38707032/67106645-edf95280-f1c2-11e9-914a-8474a733a8a9.png)

**Comment by eromano** [comment]
do you have last master branch?

**Comment by popovicsandras** [comment]
Hi @bikabdel,

Can you please check again with the latest master branch? I couldn't reproduce it, everything works fine. Please also note, there have been some changes related how to setup (the .env files) and how to start/build the application in different modes. For more information about these changes, please refer to the uptodate [README](https://github.com/Activiti/activiti-modeling-app/blob/master/README.md).
