### ISSUE TITLE
should I be able to display process definitions without a bpmndi:BPMNDiagram ?

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/activiti-modeling-app#6]
Currently if I do import a process definition that lacks the bpmndi:BPMNDiagram graphical elements then it says that it can't load the diagram. Should we add a feature to create a default layout for the elements in this case?

**Comment by ryandawsonuk** [comment]
https://issues.alfresco.com/jira/browse/APM-498

**Comment by daisuke-yoshimoto** [comment]
@ryandawsonuk 
> to display process definitions without a bpmndi:BPMNDiagram

I think that we can do it by using [bpmn-moddle-auto-layout](https://github.com/bpmn-io/bpmn-moddle-auto-layout ).
https://github.com/bpmn-io/bpmn-moddle-auto-layout

**Comment by fcorti** [comment]
Closing this because pretty outdated.
