### ISSUE TITLE
Signout doesn't work (when session expires)

### ISSUE THREAD

**Issue by doug4j** [Activiti/activiti-modeling-app#8]
> - [ ] New feature request
> - [x ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
When logged into modeling, the log out button does nothing.

**Expected behavior:**
Click on log out takes the user to a login screen where they can optionally login.

**Steps to reproduce the issue:**
1. Log into modeling.
2. Navigate to the process view.
3. Wait for the current session to timeout
4. Click on the Logout button

**Component name and version:** 

**Browser and version:** 
Chrome on Mac

**Comment by fcorti** [comment]
Closing this because it refers to an old version of the App/Engine.
