### ISSUE TITLE
How to integrate this app in my spring-boot project 

### ISSUE THREAD

**Issue by xkcoding** [Activiti/activiti-modeling-app#99]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [x] Documentation

**Current behaviour:**
I want to integrate this app into my own spring boot application, I want to use this app's page to design Activiti BPMN Diagrams.
There is some way in version 5.22, But I can't find some way in this version.

**Expected behavior:**
Give some blogs or some demos to show how to integrate, Thanks!

**Comment by MroZ11** [comment]
I agree,please

**Comment by feverdestiny** [comment]
agree++

**Comment by fcorti** [comment]
Hi @xkcoding,

Sorry for the late reply, but we are looking here after some time.
Back to your question...
What I understand you need is the designer into your own project/application.
Including this project into your own project does not seem to me the right path to follow.
From what I understand your need is to use the designer into your own application.
Instead, if you want, you can reuse the designer (it is an Open Source project), but be aware that it will require a relevant amount of effort from your side.
